- name: Start DMC runners
  hosts: all
  gather_facts: yes
  vars:
    project_dir: "{{ ansible_env.HOME }}/dmc"

  tasks:
    - name: Start runner (only if not already running)
      shell: |
        pgrep -f runner.py || nohup python3 runner.py > runner.log 2>&1 &
      args:
        chdir: "{{ project_dir }}"

- name: Wait for runners to be ready
  hosts: localhost
  tasks:
    - pause:
        seconds: 4

- name: Send training config
  hosts: all
  gather_facts: no
  vars:
    project_dir: "{{ ansible_env.HOME }}/dmc"

    config_json: >-
      {{
        {
          "nnodes": groups['all'] | length,
          "rank": groups['all'].index(inventory_hostname),
          "master_addr": hostvars[groups['master'][0]].ansible_host,
          "script": "test2.py"
        } | to_json
      }}

  tasks:
    - name: Send config to runner
      shell: |
        python3 send_config.py {{ ansible_host }} '{{ config_json }}'
      args:
        chdir: "{{ project_dir }}"